version: "3.3"
services:
  agent:
    container_name: client
    restart: unless-stopped
    build: "./agent.Dockerfile"
    network_mode: host
  server:
    container_name: server
    restart: unless-stopped
    build: "./server.Dockerfile"
    network_mode: host
