version: "3.3"
name: vm-management
services:
  ws-agent:
    container_name: ws-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./agent.Dockerfile
    network_mode: host
  ws-server:
    container_name: ws-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server.Dockerfile
    network_mode: host
