version: "3.3"
services:
  agent:
    container_name: ws-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./agent.Dockerfile
    network_mode: host
  server:
    container_name: ws-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server.Dockerfile
    network_mode: host
